### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by konradkonrad** [shutter-network/shopdemo#1]
# Functionality
- [ ] test Deposit

# Usability
- [ ] Field validation
  - [x] Receiver
  - [x] Value
  - [ ] Data (must have: validation of well-formed data. nice to have: display decoded data next to input field)
  - [ ] ABI: address
  - [ ] ABI: ints
  - [ ] ABI: hex

- [ ] Disable Deposit button while waiting for tx
- [ ] + add status message during deposit

# Buggy
- [ ] race condition: blocklistener sees block but `signer.provider` can not fetch it in `decodeShopReceipt`
- [ ] error handling when sending value to non-payable
- [x] value validation for empty field
- [ ] MM change account after connect
- [ ] shutter-provider network change on deposit: 
      `Error: network changed: 42055420 => 11155111  (event="changed", code=NETWORK_ERROR, version=6.11.1)`

# Cosmetics

- [ ] Center app view
- [ ] background over whole viewport
- [ ] Welcome header layout / items flow

# Deployment
- [ ] Remove StrictMode
- [ ] don't run dev mode

# Done

- [x] Abi Name / Selector
- [x] "You need to sign the tx before the timer runs out."
- [x] L2 Balance 0.74387934 <a>Add more.</a>
- [x] Set value `0` when clicking `Generate Calldata` on `non-payable` ABI method (regression)
- [x] Camera already in TX form 

- [x] Trying to switch to SHOP (no effect on first page load):
      `MetaMask - RPC Error: Unrecognized chain ID "0x281b6fc". Try adding the chain using wallet_addEthereumChain first`

- [x] Status messges in a box
- [x] Status order (reverse)
- [x] TXform value "in wei"
- [x] Use ABI **only** when contractData for Receiver
- [x] Logo margin.

- [x] Faucet links in Deposit page
- [x] Welcome to shutterized optimism on Sepolia. Send shutter encrypted transactions with this dApp.

- [x] "Shutter is paused. Contact https://t.me/shutter_network/1"

**Comment by fredo** [comment]
- [ ] Be able to switch account

**Comment by fredo** [comment]
>  shutter-provider network change on deposit:
Error: network changed: 42055420 => 11155111  (event="changed", code=NETWORK_ERROR, version=6.11.1)

I Think this error happens if you are already switched to sepolia
